version: '3.9'

services:
  kami-pricing-scraper:
    image: devkamico/kami-pricing-scraper:0.1.1
    container_name: pricing_scraper
    ports:
      - "8001:8001"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.kami-pricing_scraper-ratelimit.ratelimit.average=60"
      - "traefik.http.middlewares.kami-pricing_scraper-ratelimit.ratelimit.period=1m"
      - "traefik.http.middlewares.kami-pricing_scraper-ratelimit.ratelimit.burst=50"      
      - "traefik.http.routers.kami-pricing_scraper.rule=Host(`pricing.kamico.com.br`)"
      - "traefik.http.routers.kami-pricing_scraper.entrypoints=websecure"
      - "traefik.http.routers.kami-pricing_scraper.tls.certresolver=myresolver"
      - "traefik.http.routers.kami-pricing_scraper-www.rule=Host(`www.pricing.kamico.com.br`)"
      - "traefik.http.routers.kami-pricing_scraper-www.entrypoints=websecure"
      - "traefik.http.routers.kami-pricing_scraper-www.tls.certresolver=myresolver"
      - "traefik.http.routers.kami-pricing_scraper.middlewares=kami-pricing_scraper-ratelimit"
      

networks:
  proxy:
    external: true
